package com.datapreprocessor.engine;

import java.util.List;

/**
 * Generates ready-to-run Python (pandas) preprocessing code from a list of
 * {@link PreprocessingStep} descriptors collected by the UI.
 *
 * <p>The generated code is fully self-contained: it imports pandas, loads the
 * CSV file, applies every selected operation in order, and writes the cleaned
 * DataFrame back to disk.</p>
 */
public class CodeGenerator {

    // -------------------------------------------------------------------------
    // Step model
    // -------------------------------------------------------------------------

    public enum Operation {
        DROP_MISSING_ROWS,
        FILL_MISSING_MEAN,
        FILL_MISSING_MEDIAN,
        FILL_MISSING_MODE,
        FILL_MISSING_CUSTOM,
        REMOVE_DUPLICATES,
        REMOVE_OUTLIERS_IQR,
        NORMALIZE_MINMAX,
        NORMALIZE_ZSCORE,
        CAST_COLUMN
    }

    /**
     * Represents a single preprocessing step selected by the user.
     *
     * @param operation  what to do
     * @param column     target column name (may be null for row-level ops)
     * @param param      optional extra parameter (fill value, cast type, …)
     */
    public record PreprocessingStep(Operation operation, String column, String param) {
        public PreprocessingStep(Operation op)                       { this(op, null, null); }
        public PreprocessingStep(Operation op, String col)           { this(op, col, null);  }
    }

    // -------------------------------------------------------------------------
    // Code generation
    // -------------------------------------------------------------------------

    /**
     * Generates a complete Python script for the given file path and steps.
     *
     * @param csvFilePath absolute or relative path that will be embedded in the script
     * @param steps       ordered list of preprocessing operations
     * @return multi-line Python source code as a String
     */
    public String generate(String csvFilePath, List<PreprocessingStep> steps) {
        // Normalise path separators for Python
        String safePath = csvFilePath.replace("\\", "/");
        String outputPath = deriveOutputPath(safePath);

        StringBuilder sb = new StringBuilder();

        // ----- Header --------------------------------------------------------
        sb.append("# ============================================================\n");
        sb.append("# Data Preprocessor — generated by IntelliJ Data Preprocessor\n");
        sb.append("# ============================================================\n\n");

        sb.append("import pandas as pd\n");
        sb.append("import numpy as np\n\n");

        // ----- Load data -----------------------------------------------------
        sb.append("# Load dataset\n");
        sb.append(String.format("df = pd.read_csv(\"%s\")\n\n", safePath));

        sb.append("print(f\"Loaded {len(df)} rows × {len(df.columns)} columns\")\n\n");

        // ----- Operations ----------------------------------------------------
        if (steps.isEmpty()) {
            sb.append("# No preprocessing steps selected.\n\n");
        } else {
            sb.append("# ---- Preprocessing steps ----\n");
            for (PreprocessingStep step : steps) {
                sb.append(toCode(step)).append("\n");
            }
        }

        // ----- Save output ---------------------------------------------------
        sb.append("\n# Save cleaned dataset\n");
        sb.append(String.format("df.to_csv(\"%s\", index=False)\n", outputPath));
        sb.append(String.format("print(f\"Saved {len(df)} rows to '%s'\")\n", outputPath));

        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // Step → Python code
    // -------------------------------------------------------------------------

    private String toCode(PreprocessingStep step) {
        String col = step.column() != null
                ? "\"" + step.column() + "\""
                : null;

        return switch (step.operation()) {

            case DROP_MISSING_ROWS ->
                "# Drop rows with any missing value\n" +
                "df = df.dropna()\n" +
                "print(f\"After dropping missing rows: {len(df)} rows remain\")";

            case FILL_MISSING_MEAN ->
                String.format(
                    "# Fill missing values in %s with column mean\n" +
                    "df[%s] = df[%s].fillna(df[%s].mean())", col, col, col, col);

            case FILL_MISSING_MEDIAN ->
                String.format(
                    "# Fill missing values in %s with column median\n" +
                    "df[%s] = df[%s].fillna(df[%s].median())", col, col, col, col);

            case FILL_MISSING_MODE ->
                String.format(
                    "# Fill missing values in %s with column mode\n" +
                    "df[%s] = df[%s].fillna(df[%s].mode()[0])", col, col, col, col);

            case FILL_MISSING_CUSTOM -> {
                String fill = step.param() != null ? step.param() : "";
                boolean isNumeric = isNumericString(fill);
                String pyFill = isNumeric ? fill : "\"" + fill + "\"";
                yield String.format(
                    "# Fill missing values in %s with custom value\n" +
                    "df[%s] = df[%s].fillna(%s)", col, col, col, pyFill);
            }

            case REMOVE_DUPLICATES ->
                "# Remove duplicate rows\n" +
                "before = len(df)\n" +
                "df = df.drop_duplicates()\n" +
                "print(f\"Removed {before - len(df)} duplicate rows\")";

            case REMOVE_OUTLIERS_IQR ->
                String.format(
                    "# Remove outliers in %s using IQR fence\n" +
                    "_q1, _q3 = df[%s].quantile([0.25, 0.75])\n" +
                    "_iqr = _q3 - _q1\n" +
                    "_lower, _upper = _q1 - 1.5 * _iqr, _q3 + 1.5 * _iqr\n" +
                    "before = len(df)\n" +
                    "df = df[(df[%s] >= _lower) & (df[%s] <= _upper)]\n" +
                    "print(f\"Removed {{before - len(df)}} outlier rows from %s\")",
                    col, col, col, col, step.column());

            case NORMALIZE_MINMAX ->
                String.format(
                    "# Min-Max normalize %s to [0, 1]\n" +
                    "_min, _max = df[%s].min(), df[%s].max()\n" +
                    "df[%s] = (df[%s] - _min) / (_max - _min)", col, col, col, col, col);

            case NORMALIZE_ZSCORE ->
                String.format(
                    "# Z-Score standardise %s (mean=0, std=1)\n" +
                    "df[%s] = (df[%s] - df[%s].mean()) / df[%s].std()", col, col, col, col, col);

            case CAST_COLUMN -> {
                String targetType = step.param() != null ? step.param().toLowerCase() : "str";
                String pandasType = switch (targetType) {
                    case "int", "integer" -> "Int64";   // nullable integer
                    case "float", "double" -> "float64";
                    case "boolean", "bool" -> "boolean";
                    default -> "str";
                };
                yield String.format(
                    "# Cast column %s to %s\n" +
                    "df[%s] = df[%s].astype(\"%s\")", col, pandasType, col, col, pandasType);
            }
        };
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private String deriveOutputPath(String original) {
        int dot = original.lastIndexOf('.');
        return dot > 0
                ? original.substring(0, dot) + "_cleaned" + original.substring(dot)
                : original + "_cleaned";
    }

    private boolean isNumericString(String s) {
        if (s == null || s.isBlank()) return false;
        try { Double.parseDouble(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
}
