package com.datapreprocessor.engine;

import java.util.List;

/**
 * Generates ready-to-run Python (pandas) preprocessing code from a list of
 * {@link PreprocessingStep} descriptors collected by the UI.
 *
 * <p>The generated code is fully self-contained: it imports pandas, loads the
 * CSV file, applies every selected operation in order, and writes the cleaned
 * DataFrame back to disk.</p>
 */
public class CodeGenerator {

    // -------------------------------------------------------------------------
    // Step model
    // -------------------------------------------------------------------------

    public enum Operation {
        DROP_MISSING_ROWS,
        FILL_MISSING_MEAN,
        FILL_MISSING_MEDIAN,
        FILL_MISSING_MODE,
        FILL_MISSING_CUSTOM,
        REMOVE_DUPLICATES,
        REMOVE_OUTLIERS_IQR,
        NORMALIZE_MINMAX,
        NORMALIZE_ZSCORE,
        CAST_COLUMN,
        TRAIN_TEST_SPLIT,
        LABEL_ENCODE,
        ONE_HOT_ENCODE,
        SORT_COLUMN,
        FILTER_ROWS,
        NORMALIZE_ROBUST;
    }

    /**
     * Represents a single preprocessing step selected by the user.
     *
     * @param operation  what to do
     * @param column     target column name (may be null for row-level ops)
     * @param param      optional extra parameter (fill value, cast type, …)
     */
    public record PreprocessingStep(Operation operation, String column, String param) {
        public PreprocessingStep(Operation op)                       { this(op, null, null); }
        public PreprocessingStep(Operation op, String col)           { this(op, col, null);  }
    }

    // -------------------------------------------------------------------------
    // Code generation
    // -------------------------------------------------------------------------

    /**
     * Generates a complete Python script for the given file path and steps.
     *
     * @param filePath absolute or relative path that will be embedded in the script
     * @param steps       ordered list of preprocessing operations
     * @return multi-line Python source code as a String
     */
    public String generate(String filePath, List<PreprocessingStep> steps) {
        String safePath = filePath.replace("\\", "/");
        String readCall;
        if (safePath.toLowerCase().endsWith(".xlsx")) {
            readCall = "pd.read_excel(r'" + safePath + "')";
        } else if (safePath.toLowerCase().endsWith(".json")) {
            readCall = "pd.read_json(r'" + safePath + "')";
        } else {
            readCall = "pd.read_csv(r'" + safePath + "')";
        }
        // Normalise path separators for Python
        String outputPath = deriveOutputPath(safePath);

        StringBuilder sb = new StringBuilder();

        // ----- Header --------------------------------------------------------
        sb.append("# ============================================================\n");
        sb.append("# Data Preprocessor — generated by IntelliJ Data Preprocessor\n");
        sb.append("# ============================================================\n\n");

        sb.append("import pandas as pd\n");
        sb.append("import numpy as np\n\n");

        // ----- Load data -----------------------------------------------------
        sb.append("# Load dataset\n");
        sb.append(String.format("df = %s\n\n", readCall));

        sb.append("print(f\"Loaded {len(df)} rows × {len(df.columns)} columns\")\n\n");

        // ----- Operations ----------------------------------------------------
        if (steps.isEmpty()) {
            sb.append("# No preprocessing steps selected.\n\n");
        } else {
            sb.append("# ---- Preprocessing steps ----\n");
            for (PreprocessingStep step : steps) {
                sb.append(toCode(step)).append("\n");
            }
        }

        // ----- Save output ---------------------------------------------------
        // Always write cleaned output as CSV — most portable format regardless of input type
        sb.append("\n# Save cleaned dataset\n");
        sb.append(String.format("df.to_csv(\"%s\", index=False)\n", outputPath));
        sb.append(String.format("print(f\"Saved {len(df)} rows to '%s'\")\n", outputPath));

        return sb.toString();
    }


    /**
     * Generates a complete R script for the given file path and steps.
     *
     * <p>Path separators: R accepts forward slashes on all platforms, so
     * {@code filePath.replace("\\", "/")} is sufficient — no raw-string prefix needed.</p>
     *
     * <p>Library imports are emitted only for packages the script actually uses.
     * Base-R operations (na.omit, duplicated, quantile, scale, etc.) need no library.
     * File-type libraries (readxl, jsonlite) and operation libraries (fastDummies)
     * are added only when relevant.</p>
     *
     * @param filePath absolute path to the source file
     * @param steps    ordered list of preprocessing operations
     * @return multi-line R source code as a String
     */
    public String generateR(String filePath, List<PreprocessingStep> steps) {
        // ── 1. Normalise path separators ──────────────────────────────────────
        // R accepts "/" on all platforms — forward-slash normalisation is enough.
        // No raw-string prefix (r"(...)") is needed.
        String safePath    = filePath.replace("\\", "/");
        String outputPath  = deriveOutputPath(safePath);
        String lowerPath   = safePath.toLowerCase();

        // ── 2. Choose read call based on file extension ───────────────────────
        boolean isExcel = lowerPath.endsWith(".xlsx");
        boolean isJson  = lowerPath.endsWith(".json");

        String readCall;
        if (isExcel) {
            readCall = "read_excel(\"" + safePath + "\")";
        } else if (isJson) {
            readCall = "as.data.frame(fromJSON(\"" + safePath + "\"))";
        } else {
            readCall = "read.csv(\"" + safePath + "\", stringsAsFactors = FALSE)";
        }

        // ── 3. Determine which non-base libraries are actually needed ─────────
        boolean needsReadxl      = isExcel;
        boolean needsJsonlite    = isJson;
        boolean needsFastDummies = steps.stream()
                .anyMatch(s -> s.operation() == Operation.ONE_HOT_ENCODE);

        // ── 4. Build script ───────────────────────────────────────────────────
        StringBuilder sb = new StringBuilder();

        // Header
        sb.append("# ============================================================\n");
        sb.append("# Data Preprocessor — generated by IntelliJ Data Preprocessor\n");
        sb.append("# ============================================================\n\n");

        // Library block — only emit what the script uses
        if (needsReadxl)      sb.append("library(readxl)\n");
        if (needsJsonlite)    sb.append("library(jsonlite)\n");
        if (needsFastDummies) sb.append("library(fastDummies)  # install.packages(\"fastDummies\")\n");
        if (needsReadxl || needsJsonlite || needsFastDummies) sb.append("\n");

        // Load data
        sb.append("# Load dataset\n");
        sb.append("df <- ").append(readCall).append("\n");
        sb.append("cat(sprintf(\"Loaded %d rows x %d columns\\n\", nrow(df), ncol(df)))\n\n");

        // Operations
        if (steps.isEmpty()) {
            sb.append("# No preprocessing steps selected.\n\n");
        } else {
            sb.append("# ---- Preprocessing steps ----\n");
            for (PreprocessingStep step : steps) {
                sb.append(toRCode(step)).append("\n");
            }
        }

        // Save output — always CSV for portability
        sb.append("\n# Save cleaned dataset\n");
        sb.append("write.csv(df, \"").append(outputPath).append("\", row.names = FALSE)\n");
        sb.append(String.format(
                "cat(sprintf(\"Saved %%d rows to '%s'\\n\", nrow(df)))\n", outputPath));

        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // Step → Python code
    // -------------------------------------------------------------------------

    private String toCode(PreprocessingStep step) {
        String col = step.column() != null
                ? "\"" + step.column() + "\""
                : null;

        return switch (step.operation()) {

            case DROP_MISSING_ROWS ->
                "# Drop rows with any missing value\n" +
                "df = df.dropna()\n" +
                "print(f\"After dropping missing rows: {len(df)} rows remain\")";

            case FILL_MISSING_MEAN ->
                String.format(
                    "# Fill missing values in %s with column mean\n" +
                    "df[%s] = df[%s].fillna(df[%s].mean())", col, col, col, col);

            case FILL_MISSING_MEDIAN ->
                String.format(
                    "# Fill missing values in %s with column median\n" +
                    "df[%s] = df[%s].fillna(df[%s].median())", col, col, col, col);

            case FILL_MISSING_MODE ->
                String.format(
                    "# Fill missing values in %s with column mode\n" +
                    "df[%s] = df[%s].fillna(df[%s].mode()[0])", col, col, col, col);

            case FILL_MISSING_CUSTOM -> {
                String fill = step.param() != null ? step.param() : "";
                boolean isNumeric = isNumericString(fill);
                String pyFill = isNumeric ? fill : "\"" + fill + "\"";
                yield String.format(
                    "# Fill missing values in %s with custom value\n" +
                    "df[%s] = df[%s].fillna(%s)", col, col, col, pyFill);
            }

            case REMOVE_DUPLICATES ->
                "# Remove duplicate rows\n" +
                "before = len(df)\n" +
                "df = df.drop_duplicates()\n" +
                "print(f\"Removed {before - len(df)} duplicate rows\")";

            case REMOVE_OUTLIERS_IQR ->
                String.format(
                    "# Remove outliers in %s using IQR fence\n" +
                    "_q1, _q3 = df[%s].quantile([0.25, 0.75])\n" +
                    "_iqr = _q3 - _q1\n" +
                    "_lower, _upper = _q1 - 1.5 * _iqr, _q3 + 1.5 * _iqr\n" +
                    "before = len(df)\n" +
                    "df = df[(df[%s] >= _lower) & (df[%s] <= _upper)]\n" +
                    "print(f\"Removed {{before - len(df)}} outlier rows from %s\")",
                    col, col, col, col, step.column());

            case NORMALIZE_MINMAX ->
                String.format(
                    "# Min-Max normalize %s to [0, 1]\n" +
                    "_min, _max = df[%s].min(), df[%s].max()\n" +
                    "df[%s] = (df[%s] - _min) / (_max - _min)", col, col, col, col, col);

            case NORMALIZE_ZSCORE ->
                String.format(
                    "# Z-Score standardise %s (mean=0, std=1)\n" +
                    "df[%s] = (df[%s] - df[%s].mean()) / df[%s].std()", col, col, col, col, col);

            case CAST_COLUMN -> {
                String targetType = step.param() != null ? step.param().toLowerCase() : "str";
                String pandasType = switch (targetType) {
                    case "int", "integer" -> "Int64";   // nullable integer
                    case "float", "double" -> "float64";
                    case "boolean", "bool" -> "boolean";
                    default -> "str";
                };
                yield String.format(
                    "# Cast column %s to %s\n" +
                    "df[%s] = df[%s].astype(\"%s\")", col, pandasType, col, col, pandasType);
            }

            case TRAIN_TEST_SPLIT -> {
                String ratio = step.param() != null ? step.param() : "0.8";
                double trainRatio = Double.parseDouble(ratio);
                double testRatio = 1.0 - trainRatio;
                yield String.format("""
                    # Train/Test Split (%.0f%% train)
                    from sklearn.model_selection import train_test_split
                    df_train, df_test = train_test_split(df, test_size=%.2f, random_state=42)
                    print(f"Train: {len(df_train)} rows | Test: {len(df_test)} rows")
                    """,
                        trainRatio * 100,
                        testRatio);
            }
            case LABEL_ENCODE ->
                    String.format(
                            "# Label encode %s (each unique value → integer)\n" +
                                    "df[%s], _ = pd.factorize(df[%s])",
                            col, col, col);

            case ONE_HOT_ENCODE ->
                    String.format(
                            "# One-hot encode %s (expands into binary columns)\n" +
                            "df = pd.get_dummies(df, columns=[%s], dtype=int)",
                            col, col);

            case SORT_COLUMN -> {
                boolean asc = !"descending".equals(step.param());
                yield String.format(
                        "# Sort by %s (%s)\n" +
                        "df = df.sort_values(by=%s, ascending=%s).reset_index(drop=True)",
                        step.column(), asc ? "ascending" : "descending", col, asc ? "True" : "False");
            }

            case FILTER_ROWS -> {
                String raw   = step.param() != null ? step.param() : "==|";
                int    sep   = raw.indexOf('|');
                String op    = sep > 0 ? raw.substring(0, sep) : "==";
                String val   = sep >= 0 ? raw.substring(sep + 1) : "";
                boolean isNum = isNumericString(val);
                String pyVal  = isNum ? val : "\"" + val + "\"";

                String condition = switch (op) {
                    case "contains" -> String.format(
                            "df[%s].astype(str).str.contains(%s, case=False, na=False)", col, pyVal);
                    default -> String.format("df[%s] %s %s", col, op, pyVal);
                };

                yield String.format(
                        "# Filter rows: keep where %s %s %s\n" +
                        "before = len(df)\n" +
                        "df = df[%s]\n" +
                        "print(f\"Filter removed {before - len(df)} rows\")",
                        step.column(), op, val, condition);
            }

            case NORMALIZE_ROBUST ->
                    String.format(
                            "# Robust scale %s using median and IQR (resistant to outliers)\n" +
                                    "_med = df[%s].median()\n" +
                                    "_iqr = df[%s].quantile(0.75) - df[%s].quantile(0.25)\n" +
                                    "df[%s] = (df[%s] - _med) / _iqr",
                            col, col, col, col, col, col);
        };
    }

    // -------------------------------------------------------------------------
    // Step → R code
    // -------------------------------------------------------------------------

    /**
     * Converts a single {@link PreprocessingStep} to an R code snippet.
     *
     * <p>Column references use the {@code df$`col`} back-tick form so column names
     * containing spaces or special characters are always valid R identifiers.</p>
     */
    private String toRCode(PreprocessingStep step) {
        String col    = step.column();
        // Back-tick quoting handles column names with spaces / special chars
        String colRef = col != null ? "df$`" + col + "`" : null;

        return switch (step.operation()) {

            case DROP_MISSING_ROWS ->
                "# Drop rows with any missing value\n" +
                "before <- nrow(df)\n" +
                "df <- df[complete.cases(df), ]\n" +
                "cat(sprintf(\"Removed %d rows with missing values\\n\", before - nrow(df)))";

            case FILL_MISSING_MEAN ->
                String.format(
                    "# Fill missing values in %s with column mean\n" +
                    "%s[is.na(%s)] <- mean(%s, na.rm = TRUE)",
                    col, colRef, colRef, colRef);

            case FILL_MISSING_MEDIAN ->
                String.format(
                    "# Fill missing values in %s with column median\n" +
                    "%s[is.na(%s)] <- median(%s, na.rm = TRUE)",
                    col, colRef, colRef, colRef);

            case FILL_MISSING_MODE ->
                String.format(
                    "# Fill missing values in %s with column mode\n" +
                    ".mode_val <- names(sort(table(%s), decreasing = TRUE))[1]\n" +
                    "%s[is.na(%s)] <- .mode_val",
                    col, colRef, colRef, colRef);

            case FILL_MISSING_CUSTOM -> {
                String fill  = step.param() != null ? step.param() : "";
                boolean isNum = isNumericString(fill);
                String rFill  = isNum ? fill : "\"" + fill + "\"";
                yield String.format(
                    "# Fill missing values in %s with custom value\n" +
                    "%s[is.na(%s)] <- %s",
                    col, colRef, colRef, rFill);
            }

            case REMOVE_DUPLICATES ->
                "# Remove duplicate rows\n" +
                "before <- nrow(df)\n" +
                "df <- df[!duplicated(df), ]\n" +
                "cat(sprintf(\"Removed %d duplicate rows\\n\", before - nrow(df)))";

            case REMOVE_OUTLIERS_IQR ->
                String.format(
                    "# Remove outliers in %s using IQR fence\n" +
                    ".q1  <- quantile(%s, 0.25, na.rm = TRUE)\n" +
                    ".q3  <- quantile(%s, 0.75, na.rm = TRUE)\n" +
                    ".iqr <- .q3 - .q1\n" +
                    "before <- nrow(df)\n" +
                    "df <- df[!is.na(%s) & %s >= (.q1 - 1.5 * .iqr) & %s <= (.q3 + 1.5 * .iqr), ]\n" +
                    "cat(sprintf(\"Removed %%d outlier rows from %s\\n\", before - nrow(df)))",
                    col, colRef, colRef, colRef, colRef, colRef, col);

            case NORMALIZE_MINMAX ->
                String.format(
                    "# Min-Max normalize %s to [0, 1]\n" +
                    ".mn <- min(%s, na.rm = TRUE)\n" +
                    ".mx <- max(%s, na.rm = TRUE)\n" +
                    "%s <- (%s - .mn) / (.mx - .mn)",
                    col, colRef, colRef, colRef, colRef);

            case NORMALIZE_ZSCORE ->
                String.format(
                    "# Z-Score standardise %s (mean = 0, sd = 1)\n" +
                    "%s <- (%s - mean(%s, na.rm = TRUE)) / sd(%s, na.rm = TRUE)",
                    col, colRef, colRef, colRef, colRef);

            case CAST_COLUMN -> {
                String targetType = step.param() != null ? step.param().toLowerCase() : "str";
                String rFn = switch (targetType) {
                    case "int", "integer"   -> "as.integer";
                    case "float", "double"  -> "as.numeric";
                    case "boolean", "bool"  -> "as.logical";
                    default                 -> "as.character";
                };
                yield String.format(
                    "# Cast column %s to %s\n" +
                    "%s <- %s(%s)",
                    col, targetType, colRef, rFn, colRef);
            }

            case TRAIN_TEST_SPLIT -> {
                String ratio      = step.param() != null ? step.param() : "0.8";
                double trainRatio = Double.parseDouble(ratio);
                yield String.format(
                    "# Train/Test Split (%.0f%% train)\n" +
                    "set.seed(42)\n" +
                    ".idx    <- sample(nrow(df), size = floor(%.2f * nrow(df)))\n" +
                    "df_train <- df[.idx, ]\n" +
                    "df_test  <- df[-.idx, ]\n" +
                    "cat(sprintf(\"Train: %%d rows | Test: %%d rows\\n\", nrow(df_train), nrow(df_test)))",
                    trainRatio * 100, trainRatio);
            }

            case LABEL_ENCODE ->
                String.format(
                    "# Label encode %s (each unique value → integer)\n" +
                    "%s <- as.integer(factor(%s))",
                    col, colRef, colRef);

            case ONE_HOT_ENCODE ->
                String.format(
                    "# One-hot encode %s — requires fastDummies package\n" +
                    "df <- dummy_cols(df, select_columns = \"%s\", remove_selected_columns = TRUE)",
                    col, col);

            case SORT_COLUMN -> {
                boolean asc = !"descending".equals(step.param());
                yield String.format(
                    "# Sort by %s (%s)\n" +
                    "df <- df[order(%s, decreasing = %s), ]\n" +
                    "rownames(df) <- NULL",
                    col, asc ? "ascending" : "descending",
                    colRef, asc ? "FALSE" : "TRUE");
            }

            case FILTER_ROWS -> {
                String raw    = step.param() != null ? step.param() : "==|";
                int    sep    = raw.indexOf('|');
                String op     = sep > 0  ? raw.substring(0, sep)  : "==";
                String val    = sep >= 0 ? raw.substring(sep + 1) : "";
                boolean isNum = isNumericString(val);
                String rVal   = isNum ? val : "\"" + val + "\"";

                String condition = "contains".equals(op)
                        ? String.format("grepl(%s, as.character(%s), ignore.case = TRUE)", rVal, colRef)
                        : String.format("%s %s %s", colRef, op, rVal);

                yield String.format(
                    "# Filter rows: keep where %s %s %s\n" +
                    "before <- nrow(df)\n" +
                    "df <- df[%s, ]\n" +
                    "cat(sprintf(\"Filter removed %%d rows\\n\", before - nrow(df)))",
                    col, op, val, condition);
            }

            case NORMALIZE_ROBUST ->
                String.format(
                    "# Robust scale %s using median and IQR (resistant to outliers)\n" +
                    ".med <- median(%s, na.rm = TRUE)\n" +
                    ".iqr <- IQR(%s, na.rm = TRUE)\n" +
                    "%s <- (%s - .med) / .iqr",
                    col, colRef, colRef, colRef, colRef);
        };
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private String deriveOutputPath(String original) {
        int dot = original.lastIndexOf('.');
        // Always output as CSV — most portable format for cleaned data
        return dot > 0
                ? original.substring(0, dot) + "_cleaned.csv"
                : original + "_cleaned.csv";
    }

    private boolean isNumericString(String s) {
        if (s == null || s.isBlank()) return false;
        try { Double.parseDouble(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
}
